dist: xenial
language: ruby
rvm:
  - 2.5.3
cache:
  bundler: true
  directories:
    - _cache
branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - JEKYLL_ENV=production

# Travis shouldn't have to have this...
before_install:
  - gem install bundler

deploy:
  provider: pages
  local-dir: ./_site
  repo: iris-hep/iris-hep.github.io
  fqdn: iris-hep.org
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
